INSERT INTO region (nom) VALUES 
('Alaotra-Mangoro'),
('Amoron''i Mania'),
('Analamanga'),
('Analanjirofo'),
('Androy'),
('Anosy'),
('Atsimo-Andrefana'),
('Atsimo-Atsinanana'),
('Atsinanana'),
('Betsiboka'),
('Boeny'),
('Bongolava'),
('Diana'),
('Fitovinany'),
('Ihorombe'),
('Itasy'),
('Melaky'),
('Menabe'),
('Sava'),
('Sofia'),
('Vakinankaratra'),
('Vatovavy'),
('Vatovavy-Fitovinany'); 

INSERT INTO type_besoin (nom) VALUES 
('Alimentaire'),
('Médical'),
('Hébergement'),
('Vêtements'),
('Éducation'),
('Autre');